# Generated by Django 2.1.3 on 2019-07-18 14:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20190718_1906'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 18, 20, 9, 2, 599688), max_length=50),
        ),
    ]
