# Generated by Django 2.1.3 on 2019-07-18 14:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_auto_20190718_2011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 18, 20, 14, 2, 955856), max_length=50),
        ),
    ]
